import type { Lesson } from "@/lib/types";

export const module2Lessons: Lesson[] = [
  {
    id: "print-basics",
    moduleId: "m2",
    title: "print() basics",
    description: "Use print with parentheses and strings.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["print", "syntax"],
    steps: [
      {
        id: "pb-1",
        type: "intro_card",
        title: "print is a function call",
        body: "You type print, parentheses, and put the value you want to show inside.",
      },
      {
        id: "pb-2",
        type: "concept_demo",
        title: "Classic hello",
        code: "print('Hello, Python!')",
        output: "Hello, Python!",
        caption: "Parentheses wrap what you pass to print.",
      },
      {
        id: "pb-3",
        type: "multiple_choice",
        prompt: "Which line is valid Python?",
        choices: [
          "print('Hi')",
          "print 'Hi'",
          "print(Hi)",
        ],
        correctAnswer: "print('Hi')",
        explanation: "Text needs quotes; print needs parentheses in Python 3.",
      },
      {
        id: "pb-4",
        type: "predict_output",
        prompt: "What prints?",
        code: "print('7')",
        correctOutput: "7",
        explanation: "The character 7 is inside quotes, so it prints as text.",
      },
      {
        id: "pb-5",
        type: "fill_blank",
        prompt: "Type the single missing character after print.",
        code: "print___'Go')",
        correctAnswer: "(",
        explanation: "Opening parenthesis starts the argument list for print.",
        hints: ["print needs ( before the string."],
      },
      {
        id: "pb-6",
        type: "recap",
        title: "Recap",
        bullets: ["print(...) shows values.", "Strings use quotes."],
      },
      {
        id: "pb-7",
        type: "completion",
        title: "Solid",
        message: "print is your first reliable tool for seeing results.",
      },
    ],
  },
  {
    id: "strings-and-quotes",
    moduleId: "m2",
    title: "Strings and quotes",
    description: "Match quotes and treat text as data.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["strings", "quotes"],
    steps: [
      {
        id: "sq-1",
        type: "intro_card",
        title: "Text lives in strings",
        body: "A string is text in quotes. Single or double quotes work if you match them.",
      },
      {
        id: "sq-2",
        type: "multiple_choice",
        prompt: "Which is a valid string?",
        choices: ["'blue'", "blue", "'blue\""],
        correctAnswer: "'blue'",
        explanation: "Quotes must match at both ends.",
      },
      {
        id: "sq-3",
        type: "concept_demo",
        title: "Double quotes inside",
        code: "print(\"It's sunny\")",
        output: "It's sunny",
        caption: "You can choose quote style to make text easier to write.",
      },
      {
        id: "sq-4",
        type: "predict_output",
        prompt: "What prints?",
        code: "print('3' + '4')",
        correctOutput: "34",
        explanation: "The + sign joins two strings together.",
      },
      {
        id: "sq-5",
        type: "fill_blank",
        prompt: "Fill in the blank with the quoted text (include quotes).",
        code: "print(___________)",
        correctAnswer: "'hi'",
        explanation: "Wrap the text with matching single quotes.",
        hints: ["Use the same character on both sides.", "Try 'hi'"],
      },
      {
        id: "sq-6",
        type: "recap",
        title: "Recap",
        bullets: ["Strings use matching quotes.", "+ can combine strings."],
      },
      {
        id: "sq-7",
        type: "completion",
        title: "Great",
        message: "Quotes are small but important details.",
      },
    ],
  },
  {
    id: "syntax-habits",
    moduleId: "m2",
    title: "Syntax habits",
    description: "Spot parentheses, commas, and clean lines.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["syntax"],
    steps: [
      {
        id: "sh-1",
        type: "intro_card",
        title: "Syntax = spelling for code",
        body: "Small mistakes stop Python early. Build habits: parentheses, quotes, spelling.",
      },
      {
        id: "sh-2",
        type: "multiple_choice",
        prompt: "What is wrong here? print('Go'",
        choices: [
          "Missing closing parenthesis",
          "Too many prints",
          "Wrong font",
        ],
        correctAnswer: "Missing closing parenthesis",
        explanation: "Every ( needs a matching ).",
      },
      {
        id: "sh-3",
        type: "predict_output",
        prompt: "What prints?",
        code: "print('A', 'B')",
        correctOutput: "A B",
        explanation: "print can show multiple values separated by a space by default.",
      },
      {
        id: "sh-4",
        type: "fill_blank",
        prompt: "What keyword prints?",
        code: "____('test')",
        correctAnswer: "print",
        explanation: "print is the function name.",
      },
      {
        id: "sh-5",
        type: "recap",
        title: "Recap",
        bullets: ["Match parentheses.", "Match quotes.", "Read errors calmly."],
      },
      {
        id: "sh-6",
        type: "completion",
        title: "Module 2 checkpoint",
        message: "Syntax care keeps you moving fast later.",
      },
    ],
  },
];
