import type { Lesson } from "@/lib/types";

export const module4Lessons: Lesson[] = [
  {
    id: "input-basics",
    moduleId: "m4",
    title: "input() basics",
    description: "Read a line of text from the user.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["input"],
    steps: [
      {
        id: "ib-1",
        type: "intro_card",
        title: "Programs can ask questions",
        body: "input() waits for the learner to type a line and press Enter. The result is text you can store.",
      },
      {
        id: "ib-2",
        type: "concept_demo",
        title: "Prompt + read",
        code: "name = input('Your name? ')\nprint(name)",
        output: "(User types: Jordan)",
        caption: "The string inside input is the prompt shown to the user.",
      },
      {
        id: "ib-3",
        type: "multiple_choice",
        prompt: "What does input() return in Python 3?",
        choices: ["A string", "A number always", "Nothing"],
        correctAnswer: "A string",
        explanation: "Even if the user types digits, input gives you text until you convert it.",
      },
      {
        id: "ib-4",
        type: "fill_blank",
        prompt: "Fill in the function that reads user text.",
        code: "city = _____('City? ')",
        correctAnswer: "input",
        explanation: "input shows an optional prompt and returns a string.",
        hints: ["Starts with i", "Five letters"],
      },
      {
        id: "ib-5",
        type: "predict_output",
        prompt: "If the user types: Ada — what prints next?",
        code: "lang = input('Lang? ')\nprint(lang)",
        correctOutput: "Ada",
        explanation: "Whatever was typed is stored in lang, then printed.",
      },
      {
        id: "ib-6",
        type: "recap",
        title: "Recap",
        bullets: ["input() returns a string.", "Store it in a variable to reuse."],
      },
      {
        id: "ib-7",
        type: "completion",
        title: "Interactive",
        message: "You can picture a two-way conversation with input and print.",
      },
    ],
  },
  {
    id: "combining-input-output",
    moduleId: "m4",
    title: "Combining input and output",
    description: "Chain prompts, variables, and print.",
    estimatedMinutes: 5,
    difficulty: "easy",
    conceptTags: ["input", "print"],
    steps: [
      {
        id: "cio-1",
        type: "intro_card",
        title: "Read, then respond",
        body: "A common pattern: ask with input, save the answer, print something friendly.",
      },
      {
        id: "cio-2",
        type: "concept_demo",
        title: "Echo with context",
        code: "snack = input('Favorite snack? ')\nprint('Nice:', snack)",
        output: "Nice: chips",
        caption: "You can print labels and variables together.",
      },
      {
        id: "cio-3",
        type: "multiple_choice",
        prompt: "Which line reads user text into a variable called age_text?",
        choices: [
          "age_text = input('Age? ')",
          "print(age_text)",
          "age_text == input",
        ],
        correctAnswer: "age_text = input('Age? ')",
        explanation: "Assignment with input on the right stores the typed text.",
      },
      {
        id: "cio-4",
        type: "predict_output",
        prompt: "User types: blue — what prints?",
        code: "color = input('Color? ')\nprint(color)",
        correctOutput: "blue",
        explanation: "print(color) shows exactly what was stored.",
      },
      {
        id: "cio-5",
        type: "fill_blank",
        prompt: "Fill in the variable name to print its value next to the label.",
        code: "color = 'blue'\nprint('You said:', _____)",
        correctAnswer: "color",
        explanation: "Use the variable name without quotes to show its value.",
        hints: ["It matches the variable you assigned.", "color"],
      },
      {
        id: "cio-6",
        type: "recap",
        title: "Recap",
        bullets: ["input → variable → print is a core loop.", "Variables in print are not quoted."],
      },
      {
        id: "cio-7",
        type: "completion",
        title: "Smooth",
        message: "You can combine prompts and messages without feeling lost.",
      },
    ],
  },
  {
    id: "input-is-text",
    moduleId: "m4",
    title: "input is always text",
    description: "Remember strings from input until you convert.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["input", "types"],
    steps: [
      {
        id: "iit-1",
        type: "intro_card",
        title: "Strings first",
        body: "If someone types 21, input still gives you the two characters '2' and '1', not the integer 21.",
      },
      {
        id: "iit-2",
        type: "multiple_choice",
        prompt: "User types 10. What is the type of x = input('x? ')?",
        choices: ["str", "int", "float"],
        correctAnswer: "str",
        explanation: "input returns str in Python 3.",
      },
      {
        id: "iit-3",
        type: "predict_output",
        prompt: "What prints?",
        code: "a = '2'\nb = '3'\nprint(a + b)",
        correctOutput: "23",
        explanation: "Adding strings concatenates them, not math.",
      },
      {
        id: "iit-4",
        type: "concept_demo",
        title: "Contrast with numbers",
        code: "x = 2\ny = 3\nprint(x + y)",
        output: "5",
        caption: "Integers add numerically.",
      },
      {
        id: "iit-5",
        type: "recap",
        title: "Recap",
        bullets: ["input → str", "+ means join for strings, add for numbers."],
      },
      {
        id: "iit-6",
        type: "completion",
        title: "Module 4 complete",
        message: "You won’t be surprised when text acts like text.",
      },
    ],
  },
];
