import type { Lesson } from "@/lib/types";

export const module3Lessons: Lesson[] = [
  {
    id: "variables-intro",
    moduleId: "m3",
    title: "What variables are",
    description: "Store values in named boxes.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["variables"],
    steps: [
      {
        id: "vi-1",
        type: "intro_card",
        title: "A name for a value",
        body: "A variable stores information so you can reuse it later with a simple name.",
      },
      {
        id: "vi-2",
        type: "concept_demo",
        title: "Assign then use",
        code: "color = 'teal'\nprint(color)",
        output: "teal",
        caption: "= puts the value on the right into the name on the left.",
      },
      {
        id: "vi-3",
        type: "multiple_choice",
        prompt: "Which line assigns 5 to score?",
        choices: ["score = 5", "5 = score", "score == 5"],
        correctAnswer: "score = 5",
        explanation: "One equals sign assigns; two equals compare.",
      },
      {
        id: "vi-4",
        type: "predict_output",
        prompt: "What prints?",
        code: "x = 'hi'\nprint(x)",
        correctOutput: "hi",
        explanation: "x holds the string 'hi'.",
      },
      {
        id: "vi-5",
        type: "fill_blank",
        prompt: "Fill in the assignment operator.",
        code: "age ___ 20",
        correctAnswer: "=",
        explanation: "= stores a value in a variable.",
      },
      {
        id: "vi-6",
        type: "recap",
        title: "Recap",
        bullets: ["Variables have names and values.", "= assigns."],
      },
      {
        id: "vi-7",
        type: "completion",
        title: "Nice",
        message: "You can read simple assignments fluently.",
      },
    ],
  },
  {
    id: "naming-variables",
    moduleId: "m3",
    title: "Naming variables",
    description: "Use clear names and valid spelling.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["naming"],
    steps: [
      {
        id: "nv-1",
        type: "intro_card",
        title: "Names are for humans",
        body: "Python cares about spelling. Future-you cares about meaning. Pick clear names.",
      },
      {
        id: "nv-2",
        type: "multiple_choice",
        prompt: "Which name is a good fit for a favorite food?",
        choices: ["favorite_food", "x", "123thing"],
        correctAnswer: "favorite_food",
        explanation: "Letters and underscores work; 123thing starts invalidly with digits.",
      },
      {
        id: "nv-3",
        type: "concept_demo",
        title: "Snake case",
        code: "user_name = 'Lee'\nprint(user_name)",
        output: "Lee",
        caption: "Underscores separate words in variable names.",
      },
      {
        id: "nv-4",
        type: "predict_output",
        prompt: "What prints?",
        code: "pet = 'Rio'\nprint(pet)",
        correctOutput: "Rio",
        explanation: "pet points to the string Rio.",
      },
      {
        id: "nv-5",
        type: "recap",
        title: "Recap",
        bullets: ["Use descriptive names.", "Avoid starting with digits."],
      },
      {
        id: "nv-6",
        type: "completion",
        title: "Great naming",
        message: "Readable names reduce bugs.",
      },
    ],
  },
  {
    id: "updating-values",
    moduleId: "m3",
    title: "Updating values",
    description: "Change what a variable points to.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["assignment"],
    steps: [
      {
        id: "uv-1",
        type: "intro_card",
        title: "Variables can change",
        body: "You can assign again. The name now refers to the new value.",
      },
      {
        id: "uv-2",
        type: "concept_demo",
        title: "Reassign",
        code: "score = 1\nscore = 2\nprint(score)",
        output: "2",
        caption: "The last assignment wins for what print sees.",
      },
      {
        id: "uv-3",
        type: "predict_output",
        prompt: "What prints?",
        code: "n = 3\nn = n + 1\nprint(n)",
        correctOutput: "4",
        explanation: "n + 1 uses the current n (3), so n becomes 4.",
      },
      {
        id: "uv-4",
        type: "multiple_choice",
        prompt: "After x = 2 then x = x + 1, what is x?",
        choices: ["3", "2", "1"],
        correctAnswer: "3",
        explanation: "Add one to the old value, store back into x.",
      },
      {
        id: "uv-5",
        type: "fill_blank",
        prompt: "Fill in to add 10 to total.",
        code: "total = total ___ 10",
        correctAnswer: "+",
        explanation: "+ adds numbers.",
      },
      {
        id: "uv-6",
        type: "recap",
        title: "Recap",
        bullets: ["Reassignment updates the value.", "n = n + 1 is common."],
      },
      {
        id: "uv-7",
        type: "completion",
        title: "Module 3 done",
        message: "Variables now feel flexible, not mysterious.",
      },
    ],
  },
];
