import type { Lesson } from "@/lib/types";

export const module1Lessons: Lesson[] = [
  {
    id: "what-programming-is",
    moduleId: "m1",
    title: "What programming is",
    description: "Build a mental model of programs as instructions.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["programming-basics"],
    steps: [
      {
        id: "wpi-1",
        type: "intro_card",
        title: "Programs are instructions",
        body: "A program is a precise list of steps a computer follows. Think of it like a recipe: clear steps, in order.",
      },
      {
        id: "wpi-2",
        type: "concept_demo",
        title: "Tiny program, clear result",
        code: "print('Hello')",
        output: "Hello",
        caption: "Python reads the line and shows text on the screen.",
      },
      {
        id: "wpi-3",
        type: "multiple_choice",
        prompt: "What does a program mainly give the computer?",
        choices: [
          "A list of instructions to follow",
          "A random idea",
          "A single picture only",
        ],
        correctAnswer: "A list of instructions to follow",
        explanation: "Programs are step-by-step instructions, not vague ideas.",
        hints: [
          "Think: recipe vs doodle.",
          "Computers need clear steps.",
        ],
      },
      {
        id: "wpi-4",
        type: "predict_output",
        prompt: "What prints when this runs?",
        code: "print('Hi')",
        correctOutput: "Hi",
        explanation: "print shows the text inside the quotes.",
        hints: ["Look inside the quotes.", "There is no extra word like Hello."],
      },
      {
        id: "wpi-5",
        type: "recap",
        title: "Quick recap",
        bullets: [
          "Programs are ordered instructions.",
          "Python can show output with print.",
        ],
      },
      {
        id: "wpi-6",
        type: "completion",
        title: "Nice work",
        message: "You connected ideas to real code. Next: what makes Python special.",
      },
    ],
  },
  {
    id: "what-python-is",
    moduleId: "m1",
    title: "What Python is",
    description: "See where Python fits and why beginners use it.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["python-role"],
    steps: [
      {
        id: "wpy-1",
        type: "intro_card",
        title: "Python is a language",
        body: "Python is a programming language: a set of rules for writing instructions humans and tools can share.",
      },
      {
        id: "wpy-2",
        type: "multiple_choice",
        prompt: "Python is best described as…",
        choices: [
          "A programming language",
          "A type of computer hardware",
          "A website browser",
        ],
        correctAnswer: "A programming language",
        explanation: "Languages describe instructions; hardware runs them.",
      },
      {
        id: "wpy-3",
        type: "concept_demo",
        title: "Readable first steps",
        code: "name = 'Asha'\nprint(name)",
        output: "Asha",
        caption: "Short programs can look close to plain English.",
      },
      {
        id: "wpy-4",
        type: "fill_blank",
        prompt: "Fill in the function that shows output.",
        code: "___('Ready')",
        correctAnswer: "print",
        explanation: "print sends text to the screen in Python.",
        hints: ["Starts with p", "Five letters"],
      },
      {
        id: "wpy-5",
        type: "predict_output",
        prompt: "What prints?",
        code: "print('Py')",
        correctOutput: "Py",
        explanation: "The quotes wrap the exact characters printed.",
      },
      {
        id: "wpy-6",
        type: "recap",
        title: "Recap",
        bullets: [
          "Python is a language, not hardware.",
          "print shows text output.",
        ],
      },
      {
        id: "wpy-7",
        type: "completion",
        title: "You’re set",
        message: "You can explain what Python is in one sentence.",
      },
    ],
  },
  {
    id: "from-code-to-result",
    moduleId: "m1",
    title: "From code to result",
    description: "Trace how Python runs a line and shows output.",
    estimatedMinutes: 5,
    difficulty: "easy",
    conceptTags: ["execution", "output"],
    steps: [
      {
        id: "fcr-1",
        type: "intro_card",
        title: "Run means read and act",
        body: "Python reads your file from top to bottom and runs one statement at a time.",
      },
      {
        id: "fcr-2",
        type: "concept_demo",
        title: "Order matters",
        code: "print('First')\nprint('Second')",
        output: "First\nSecond",
        caption: "Each line runs in order.",
      },
      {
        id: "fcr-3",
        type: "multiple_choice",
        prompt: "Which prints first?",
        code: "print('A')\nprint('B')",
        choices: ["A", "B", "Both at once"],
        correctAnswer: "A",
        explanation: "Python runs the first line, then the second.",
      },
      {
        id: "fcr-4",
        type: "predict_output",
        prompt: "What is the full output?",
        code: "print('1')\nprint('2')",
        correctOutput: "1\n2",
        explanation: "Two lines of output, in order, separated by a newline.",
        hints: ["Two print lines → two lines out.", "No commas between lines."],
      },
      {
        id: "fcr-5",
        type: "fill_blank",
        prompt: "Which keyword prints?",
        code: "___('done')",
        correctAnswer: "print",
        explanation: "print is the built-in way to show text output.",
        hints: ["Built-in function, lowercase."],
      },
      {
        id: "fcr-6",
        type: "recap",
        title: "Recap",
        bullets: [
          "Python runs top to bottom.",
          "Each print can add another line of output.",
        ],
      },
      {
        id: "fcr-7",
        type: "completion",
        title: "Module 1 complete",
        message: "You can trace simple programs mentally. On to syntax details.",
      },
    ],
  },
];
