import type { Lesson } from "@/lib/types";

export const module5Lessons: Lesson[] = [
  {
    id: "types-overview",
    moduleId: "m5",
    title: "Types at a glance",
    description: "See str, int, float, and bool in context.",
    estimatedMinutes: 5,
    difficulty: "easy",
    conceptTags: ["types"],
    steps: [
      {
        id: "to-1",
        type: "intro_card",
        title: "Values have types",
        body: "Python tracks what kind of value something is: text, whole numbers, decimals, or true/false.",
      },
      {
        id: "to-2",
        type: "concept_demo",
        title: "type() peek",
        code: "print(type('hi'))\nprint(type(7))",
        output: "<class 'str'>\n<class 'int'>",
        caption: "type(...) tells you the kind of value.",
      },
      {
        id: "to-3",
        type: "multiple_choice",
        prompt: "Which value is an int?",
        choices: ["9", "'9'", "9.0"],
        correctAnswer: "9",
        explanation: "Without quotes, 9 is an integer literal.",
      },
      {
        id: "to-4",
        type: "predict_output",
        prompt: "What prints?",
        code: "print(type(False))",
        correctOutput: "<class 'bool'>",
        explanation: "False is a boolean value.",
      },
      {
        id: "to-5",
        type: "fill_blank",
        prompt: "Fill in the type name for text.",
        code: "print(type('a'))  # <class '____'>",
        correctAnswer: "str",
        explanation: "Strings have type str.",
      },
      {
        id: "to-6",
        type: "recap",
        title: "Recap",
        bullets: ["str, int, float, bool are common starters.", "Quotes make strings."],
      },
      {
        id: "to-7",
        type: "completion",
        title: "Typed",
        message: "You can name the big four types confidently.",
      },
    ],
  },
  {
    id: "numbers-and-text",
    moduleId: "m5",
    title: "Numbers vs text",
    description: "Do math on numbers, join text carefully.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["int", "float", "strings"],
    steps: [
      {
        id: "nat-1",
        type: "intro_card",
        title: "Mix with care",
        body: "Math operators expect numbers. The plus sign joins strings instead when both sides are text.",
      },
      {
        id: "nat-2",
        type: "predict_output",
        prompt: "What prints?",
        code: "print(2 + 3)",
        correctOutput: "5",
        explanation: "Both are ints, so + adds.",
      },
      {
        id: "nat-3",
        type: "predict_output",
        prompt: "What prints?",
        code: "print('2' + '3')",
        correctOutput: "23",
        explanation: "Both are strings, so + joins.",
      },
      {
        id: "nat-4",
        type: "multiple_choice",
        prompt: "Which expression is valid if name is a string?",
        choices: [
          "print('Hi ' + name)",
          "print('Hi ' - name)",
          "print('Hi ' * name)",
        ],
        correctAnswer: "print('Hi ' + name)",
        explanation: "+ joins strings; other operators are not for combining text this way.",
      },
      {
        id: "nat-5",
        type: "fill_blank",
        prompt: "Fill in to turn the text '8' into an integer before adding 2.",
        code: "print(___('8') + 2)",
        correctAnswer: "int",
        explanation: "int(...) converts a string of digits to an integer.",
      },
      {
        id: "nat-6",
        type: "recap",
        title: "Recap",
        bullets: ["Check if values are text vs numbers.", "Convert when you need math."],
      },
      {
        id: "nat-7",
        type: "completion",
        title: "Clearer",
        message: "You can predict + by checking the types involved.",
      },
    ],
  },
  {
    id: "true-and-false",
    moduleId: "m5",
    title: "True and False",
    description: "Booleans power decisions later.",
    estimatedMinutes: 4,
    difficulty: "easy",
    conceptTags: ["boolean"],
    steps: [
      {
        id: "tf-1",
        type: "intro_card",
        title: "Booleans are answers",
        body: "Boolean values are True or False. They often come from comparisons like == or <.",
      },
      {
        id: "tf-2",
        type: "concept_demo",
        title: "Compare numbers",
        code: "print(3 < 5)\nprint(3 == 3)",
        output: "True\nTrue",
        caption: "Comparisons evaluate to booleans.",
      },
      {
        id: "tf-3",
        type: "multiple_choice",
        prompt: "What does print(4 == 5) show?",
        choices: ["False", "True", "4"],
        correctAnswer: "False",
        explanation: "4 is not equal to 5.",
      },
      {
        id: "tf-4",
        type: "predict_output",
        prompt: "What prints?",
        code: "print(True and False)",
        correctOutput: "False",
        explanation: "and needs both sides true to be True.",
      },
      {
        id: "tf-5",
        type: "fill_blank",
        prompt: "Fill in the comparison operator for equality.",
        code: "print(1 ___ 1)",
        correctAnswer: "==",
        explanation: "== checks equality; = assigns.",
      },
      {
        id: "tf-6",
        type: "recap",
        title: "Recap",
        bullets: ["Booleans are True/False.", "Comparisons produce booleans."],
      },
      {
        id: "tf-7",
        type: "completion",
        title: "Course-ready",
        message: "You’re ready for conditionals with solid type intuition.",
      },
    ],
  },
];
